import Head from 'next/head'
// import Card from '../components/card.js'
import Card from '../components/card.js'

export default function Home( { props }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Card className='main' title="placeholder title" desc="placeholder description" image="https://picsum.photos/2000/3000" />
        </div>
      </main>
    </>
  ) 
}

// export async function getServerSideProps() {
//   const response = await fetch('https://jsonplaceholder.typicode.com/posts')
//   const data = await response.json()

//   return {
//     props: {
//       articles: data,
//     },
//   }
// }
