import Head from 'next/head'
import Card from '../components/card.js'
import { useState, useEffect } from "react";
import Button from '@mui/material/Button';
import Error from 'next/error';

export default function Home( { errorCode, entries }) {
  if (errorCode) {
    return <Error statusCode={errorCode} />
  } 

  const [visible, setVisible] = useState(5);
  const [cards, setCards] = useState(entries.slice(0, visible));

  useEffect(() => {
      setCards(entries.slice(0, visible));
    }, [visible]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {
            cards.map((entry) => (
              <Card title={entry.title} desc={entry.description} image={entry.url} />            
          ))}
          <Button 
            size="small" 
            variant="contained" 
            onClick={() => setVisible(visible + 5)} 
          > 
            Load More
          </Button>
        </div>
      </main>
    </>
  ) 
}

export async function getServerSideProps() {
  // const response = await fetch('https://mock.codes/500');
  const response = await fetch('https://api.slingacademy.com/v1/sample-data/photos?limit=50');
  const data = await response.json();
  if (response?.ok) {
    return {
      props: { 
        entries: data.photos,
        errorCode: false
      }
    }
  } else {
    return { 
      props: {
        entries: [], 
        errorCode: data.statusCode
      }
    }
  }
}
